name             'passenger_nginx_vhost_test'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures passenger_nginx_vhost_test'
long_description 'Installs/Configures passenger_nginx_vhost_test'
version          '0.1.0'
depends 'passenger_nginx'
